---
# tasks file for networking

- name: NetworkManager config
  ini_file: >
    dest={{ nm_config_file }}
    section=main
    option=monitor-connection-files
    value=true
  notify: restart NetworkManager

# Firewall config

- name: install apt packages
  apt: pkg=ufw update_cache=yes cache_valid_time=3600

- name: allow ssh
  ufw: rule=limit port=ssh proto=tcp

- name: enable ufw and configure the default policy
  ufw: state=enabled policy=deny logging=off
