#!/usr/bin/env ansible-playbook

# local.yml is played by ansible-pull after each pull.

---

- hosts: localhost
  remote_user: root

  vars:
    bookkeepingdir: /var/lib/ansible/bookkeeping

  pre_tasks:
  - name: Creating the bookkeeping dir
    file: path={{ bookkeepingdir }} state=directory owner=root group=root mode=0755

  roles:
  - role: networking
  - role: printing
  - role: email
  - role: admin
