---
# tasks file for printing

- name: install dependency packages with apt
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 autoremove=yes
  with_items:
    - cups-client
    - smbclient

# Doesn't work.  If there is e.g. white space before worgroup variable
# in the existing smb.conf file, ini_file module just doesn't do.
#- name: Samba workgroup config
#  ini_file: >
#    dest={{ samba_config_file }}
#    section=global
#    option=workgroup
#    value=ATKK
#  become: True

- name: hyad printer config script
  template: src=hyad_printing.sh.j2 dest=/usr/local/sbin/hyad_printing.sh mode=0744 owner=root group=root
  become: True

- name: Run config script
  command: /usr/local/sbin/hyad_printing.sh creates={{ bookkeepingdir }}/{{ adprint_touch_file }}
  become: True
